language: node_js
node_js:
  - '15.3.0'
os:
  - osx
install:
  - npm ci
jobs:
  include:
    - name: lint
      script: npm run lint
    - name: track
      script: npm run tracker
    - name: test
      before_install:
        - npm i -g codecov
      script:
          - npm test
          - codecov