language: node_js
node_js:
  - '12.13.0'
os:
  - osx
jobs:
  include:
    - stage: test
      install:
        - npm install -g codecov
        - npm ci
      script:
        - npm test
        - codecov
        - npm run tracker
    - stage: lint
      install:
        - npm ci
      script: npm run lint
